logo: # add logo name
title: Stock Betico
description: > # this means to ignore newlines until "baseurl:"
  Este sitio fue creado para aprender herraminetas TICs y  promocionar productos que tiene mi madre en stock, apoyenla! yanbal, Selva Alegre, Sangolquí, Ecuador
permalink: ':title/'
baseurl: "/bef" # the subpath of your site, e.g. /blog
url: "https://betty-c.github.io/bef/" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: yanbal.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: oso.jpg # your photo
author-name: Betty Cuichán #your name
about-author:   Este sitio fue creado para promocionar productos que tengo en stock y aprender herramientas TICs   # about author
phone: 0995957267 Betty Cuichán # your pnone number
email:  # your email
website:  # you website

# Social link
#google_url:    # add url link
#witter_url:   # add url link
#instagram_url: # add url link
#pinterest_url: # add url link
#dribbble_url:  # add url link
#facebook_url:  # add url link

# Disqus
discus_identifier:  # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics: UA-182336801-1

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
